
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DOT HASH LPAREN RPAREN VARIABLEexpression : VARIABLEexpression : HASH VARIABLE DOT expressionexpression : LPAREN expression expression RPAREN'
    
_lr_action_items = {'VARIABLE':([0,2,3,4,6,7,9,10,],[2,-1,5,2,2,2,-2,-3,]),'HASH':([0,2,4,6,7,9,10,],[3,-1,3,3,3,-2,-3,]),'LPAREN':([0,2,4,6,7,9,10,],[4,-1,4,4,4,-2,-3,]),'$end':([1,2,9,10,],[0,-1,-2,-3,]),'RPAREN':([2,8,9,10,],[-1,10,-2,-3,]),'DOT':([5,],[7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,4,6,7,],[1,6,8,9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> VARIABLE','expression',1,'p_expression_variable','parser_1.py',6),
  ('expression -> HASH VARIABLE DOT expression','expression',4,'p_expression_lambda','parser_1.py',10),
  ('expression -> LPAREN expression expression RPAREN','expression',4,'p_expression_application','parser_1.py',14),
]
